{% set name = "django_unicorn" %}
{% set version = "0.62.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dedf97e4c59e288537911c995a6d0c08615bd3274bb77b43e8031f4c2d365082

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4
    - pip
    - poetry-core
  run:
    - python >=3.7,<4
    - django >=2.2
    - beautifulsoup4 >=4.8.0
    - orjson >=3.6.0,<4.0.0
    - shortuuid >=1.0.1,<2.0.0
    - cachetools >=4.1.1,<5.0.0
    - decorator >=4.4.2,<5.0.0
    # - dataclasses >=0.8.0, <1.0.0  # python <3.7

test:
  imports:
    - django_unicorn
    - django_unicorn.call_method_parser
    - django_unicorn.db
    - django_unicorn.decorators
    - django_unicorn.errors
    - django_unicorn.serializer
    - django_unicorn.settings
    - django_unicorn.urls
    - django_unicorn.utils
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://www.django-unicorn.com/
  summary: The magical reactive component framework for Django
  description: |
    Unicorn adds modern reactive component functionality to your Django templates 
    without having to learn a new templating language or fight with complicated 
    JavaScript frameworks. It seamlessly extends Django past its server-side framework
    roots without giving up all of its niceties or forcing you to re-building your
    application. With Django Unicorn, you can quickly and easily add rich front-end
    interactions to your templates, all while using the power of Django.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://www.django-unicorn.com/docs/
  dev_url: https://github.com/adamghill/django-unicorn

extra:
  recipe-maintainers:
    - jacksund
